spring.application.name=livro-caixa

# ? DESATIVA H2
# spring.datasource.url=jdbc:h2:file:./data/livro-caixa
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# ? ATIVA POSTGRES
spring.datasource.url=jdbc:postgresql://dpg-d706k2chg0os73a60890-a:5432/livro_caixa_db_casu
spring.datasource.username=livro_caixa_db_casu_user
spring.datasource.password=TiFFpkY8VnoCKpucNkF9L6oz1YHumN2z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
