spring.datasource.url=jdbc:postgresql://dpg-d706k2chg0os73a60890-a.oregon-postgres.render.com:5432/livro_caixa_db_casu
spring.datasource.username=livro_caixa_db_casu_user
spring.datasource.password=TiFFpkY8VnoCKpucNkF9L6ozlYHumN2z

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
